My ai
ObelusFamily/Anythink-Market-cc4ax pull request #5
Opened 2022-11-23 19:59 UTC by aloncarmel

- Adding open ai imge url
- Adding open ai imge url
- ai

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

2022-11-23 19:59 UTC, vanessa-cooper commented
On it! I'll review the changes as soon as possible!

2022-11-23 20:00 UTC, vanessa-cooper requested changes
Looks like we have a few checks failing. Please try again and make sure they all pass.

2022-11-23 21:52 UTC, aloncarmel commented
בחייט נס. תאשרי, אני פה עייף ורוצה לישון

2022-11-23 21:52 UTC, aloncarmel commented
נס תעזרי לי נננסנסססססססס איפה הלכת לישון כבר

2022-11-23 21:52 UTC, aloncarmel commented
ערה?

2022-11-23 21:56 UTC, aloncarmel commented
נס תעני לי נס

2022-11-24 05:31 UTC, or-yam approved these changes
LGTM 🤖

![Alt Text](https://media.giphy.com/media/l0MYHEI0xktKCVjri/giphy.gif)

2022-11-24 05:31 UTC, or-yam commented on backend/package.json
> +    "openai":"*"
Why not to specify the version ?

2022-11-24 05:31 UTC, or-yam commented on backend/routes/api/items.js
> +//Done j
🤨

2022-11-24 08:07 UTC, aloncarmel commented on backend/routes/api/items.js
> +//Done j
Fixed

2022-11-24 08:07 UTC, aloncarmel commented on backend/package.json
> +    "openai":"*"
Fixed

2022-11-24 08:47 UTC, or-yam approved these changes

2022-11-24 09:30 UTC, vanessa-cooper approved these changes
Looking good! You can merge the PR now.

2022-11-24 09:31 UTC, merged